#!/usr/bin/env bash

REPO_NAME="python-flask-nginx"

#checkout the newest version of the code
export GIT_WORK_TREE="/var/git/${REPO_NAME}"
git checkout -f

TAG="$(git log --pretty=format:'%h' -n 1)"
FULL_COMMIT_TAG="${REPO_NAME}:${TAG}"
FULL_LATEST_TAG="${REPO_NAME}:latest"

# Build the image with the proper commit tag
docker build -t "${FULL_LATEST_TAG}" "${GIT_WORK_TREE}"

# Get the Docker IF of the latest built image
DOCKER_ID="$(docker images -q ${REPO_NAME} | HEAD -1)"

# Tag the latest version based off a commit tag.
# docker tag -f "${DOCKER_ID}" "${FULL_LATEST_TAG}"

echo "Restarting ${REPO_NAME}"
docker stop "${REPO_NAME}"

echo "Removing untagged Docker images (may take a while)"
docker rmi $(docker images --quiet --filter "dangling=true")

docker stop "nginx"